# Generated by Django 2.0.7 on 2018-07-16 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_content',
            field=models.CharField(default=34, max_length=280),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
