# Generated by Django 2.0.7 on 2018-07-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20180726_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(default='seda', max_length=128),
            preserve_default=False,
        ),
    ]
